### ISSUE TITLE
Finish Graphite support for 2.0.0

### ISSUE THREAD

**Issue by edeckers** [alhardy/AppMetrics.Extensions.Graphite#19]
The Graphite reporter is not fully refactored for 2.0.0, which renders it unusable in .net core 2.0

**Comment by MaxDeg** [comment]
hey, what still needs to be done in order to have a 2.0.0 pre-release of Graphite reporting? Could I help?

**Comment by alhardy** [comment]
@MaxDeg Thanks for offering! Still need to investigate, I was concentrating on App Metrics core before taking a break over xmas to date. I need to get a few things sorted in App Metrics core before looking into the Graphite reporter, it would be very helpful if you're able to give the reporter a run with the lastest App Metrics core to determine what needs to be refactored.

**Comment by MaxDeg** [comment]
Alright, I will try do it today or tomorrow. I will keep you in touch

**Comment by MaxDeg** [comment]
I got a look at the code. 
- Formatters and Reporting projects look good.
- The test project does not compile, there is a lot of dependencies on GraphiteReporterProvider (which I assume is from the v1)
- The sandbox can be easily updated, except for the samplerequests class that use a scheduler. For what I understood new reporters use a new project to do it.

For the tests I will try to understand how the project works to implement them.

**Comment by alhardy** [comment]
Just getting back on finishing this off, after releasing other App Metrics packages. 

Keen to give [Hosted Metrics](https://grafana.com/cloud/metrics) a go for production usage which is Graphite compat.

**Comment by alhardy** [comment]
@MaxDeg Any change you could do some testing using the dev build package on [MyGet](https://www.myget.org/feed/appmetrics/package/nuget/App.Metrics.Formatters.Graphite)?

**Comment by MaxDeg** [comment]
I will try to do some test this week

**Comment by MaxDeg** [comment]
Ok I've done some testing with the reporting.

Here is the setup I used:
```csharp
var metricsBuilder = AppMetrics.CreateDefaultBuilder();
            metricsBuilder.Configuration.Configure(opts =>
            {
                opts.GlobalTags.Add("service-name", "echo-service");
                opts.AddServerTag("localhost");
            });
            metricsBuilder.Report.ToGraphite("net.tcp://my-host", TimeSpan.FromSeconds(10));

            services.AddMetrics(metricsBuilder.Build());
            services.AddMetricsReportScheduler();
            services.AddMetricsTrackingMiddleware();
            services.AddMetricsEndpoints();
```

I found multiple issues.

data are not pushed to graphite 
-----------------------------------
I get an error of type `System.IO.IOException: 'Authentication failed because the remote party has closed the transport stream.'`  and after that exception I have exception of type Object Disposed in DefaultGraphiteTcpClient at line 55.

But it looks like that first call to Graphite is working well because I can see the variables in graphite web interface (with the proper name of the application and with the tags I have defined). The flush of the data are not working.

NLog issue
------------
I use NLog for logging in my project with custom layout renderer. 
I get some error at init about "app metrics" NLog failing to find renderer:
`System.ArgumentException: 'LayoutRenderer cannot be found: 'application-type''`
I assume that it's because "App Metrics logs" are redirected to my logger with my custom layout.

I use this docker image as my graphite host: https://hub.docker.com/r/kamon/grafana_graphite/

**Comment by MaxDeg** [comment]
After further investigation looks like this version is working better in my case:
```csharp
public async Task<GraphiteWriteResult> WriteAsync(string payload, CancellationToken cancellationToken = default(CancellationToken))
        {
            if (payload == null)
            {
                return GraphiteWriteResult.SuccessResult;
            }

            if (NeedToBackoff())
            {
                return new GraphiteWriteResult(false, "Too many failures in writing to Graphite, Circuit Opened - TCP");
            }

            try
            {
                using (var client = new TcpClient { SendTimeout = _timeout })
                {
                    Logger.Trace("Opening TCP Connection for Graphite");
                    await client.ConnectAsync(_options.BaseUri.Host, _options.BaseUri.Port);

                    using (var stream = client.GetStream())
                    {
                        using (var writer = new StreamWriter(stream) { NewLine = "\n" })
                        {
                            await writer.WriteLineAsync(payload);

                            await writer.FlushAsync();
                        }

                        await stream.FlushAsync(cancellationToken);

                        Logger.Trace("Successful write to Graphite - TCP");

                        return new GraphiteWriteResult(true);
                    }
                }
            }
            catch (Exception ex)
            {
                Interlocked.Increment(ref _failureAttempts);
                Logger.Error(ex, "Failed to write to Graphite - TCP");
                return new GraphiteWriteResult(false, ex.ToString());
            }
        }
```

**Comment by alhardy** [comment]
Can you PR if that's the case, will do some testing too
